version: '2'

volumes:
  winedb:

services:
  postgres:
    build: ./postgres
    volumes:
      - winedb:/var/lib/postgresql/data
      - ./:/app
    environment:
      POSTGRES_DB: wine_price
      POSTGRES_USER: postgres

  pgt:
    build: ./pgt
#    volumes:
#      - ./config/postgrest.conf:/etc/postgrest.conf
#      - ./config/nginx_envsubst.conf:/nginx_envsubst.conf
    ports:
      - "8080:80"
    environment:
      - PGT_JWT=***REMOVED***
      - PGT_HOST=wine-api.library.ucdavis.edu
    links:
      - postgres:postgres
    depends_on:
      - postgres
#    command: ls

  sync:
    build: ./firebase-sync
    depends_on:
      - postgres
