version: '2'

volumes:
  winedb:

services:
  postgres:
    build: ./postgres
    volumes:
      - winedb:/var/lib/postgresql/data
      - ./:/app
    environment:
      POSTGRES_DB: wine_price_dev
      POSTGRES_USER: postgres

  postgrest:
    build: ./postgrest
    volumes:
      - ./config/postgrest.conf:/etc/postgrest.conf
    links:
      - postgres:postgres
    depends_on:
      - postgres

  nginx:
    image: nginx
    volumes:
      - .:/app
    ports:
      - "8081:80"
    environment:
      - NGINX_HOST=api.catalogs.qjhart.org
      - NGINX_PORT=80
    links:
      - postgrest:postgrest
    command: /bin/bash -c "envsubst < /app/config/nginx_envsubst.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  sync:
    build: ./firebase-sync
    depends_on:
      - postgres