version: '2'

volumes:
  winedb:

services:
  postgres:
    build: ../postgres
    volumes:
      - winedb:/var/lib/postgresql/data
      - ../:/app
    environment:
      POSTGRES_DB: wine_price
      POSTGRES_USER: postgres

  pgt:
    build: ../pgt
    ports:
      - "8082:80"
    environment:
      # Auth0: Price the Vintage - Dev
      - PGT_JWT=${PGT_JWT}
      - PGT_HOST=dev-wine-api.library.ucdavis.edu
    links:
      - postgres:postgres
    depends_on:
      - postgres

  sync:
    build: ../firebase-sync
    depends_on:
      - postgres
    environment:
      PRICE_THE_VINTAGE_ENV: dev